# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-helloWorld"
BBFILE_PATTERN_meta-helloWorld = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-helloWorld = "6"

LAYERDEPENDS_meta-helloWorld = "core"
LAYERSERIES_COMPAT_meta-helloWorld = "scarthgap"


# Throttle thread counts to prevent Out-of-Memory Error
BB_NUMBER_THREADS = "2"
PARALLEL_MAKE = "-j 2"

# Force GCC to compile single-threaded to prevent Out of Memory Crash
PARALLEL_MAKE:pn-gcc = "-j 1"
PARALLEL_MAKE:pn-gcc-cross-aarch64 = "-j 1"
PARALLEL_MAKE:pm-gcc-runtime = "-j 1"


# Set Target Hardware
MACHINE ?= "qemuarm64"


#Include the custom application in the final image automatically
IMAGE_INSTALL:append = " helloworld"
